spring.datasource.url=jdbc:mysql://localhost:3306/hostsports
spring.datasource.username=root
spring.datasource.password=Rajvardhan007@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


//security.jwt.secret-key=1234567890123456789012345678901234567890123456789012345678901234
//security.jwt.expiration-ms=86400000

security.jwt.secret-key=MzIxNjU0OTg3NjU0MzIxNjU0OTg3NjU0MzIxNjU0OTg3NjU0MzIxNjU0OTg3NjU0MzIx
security.jwt.expiration-ms=3600000
security.jwt.refresh-expiration-ms=604800000

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.1