apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostsports-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hostsports
  template:
    metadata:
      labels:
        app: hostsports
    spec:
      containers:
        - name: hostsports
          image: hostsports:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: hostsports-config
            - secretRef:
                name: hostsports-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15