apiVersion: v1
kind: Secret
metadata:
  name: hostsports-secret
type: Opaque
stringData:
  DB_USERNAME: "hostsports_user"
  DB_PASSWORD: "change-me-in-real-deployment"
  JWT_SECRET: "change-me-too-use-a-real-256-bit-key"